"""Joint simulation of the index, its variance and the short rate.

The liability is a forty-year claim on an equity account discounted at a stochastic rate, so
the simulator has to get three things right at once: the index, the volatility that decides
how often the guarantee bites, and the curve that decides what the payments are worth.
Getting any one of them right in isolation is not enough, because the correlation between
them is most of the answer. Rates falling while equity falls is the state that makes this
liability expensive, and a model with deterministic rates cannot produce it.

Three choices are worth defending before the code.

*Variance uses Andersen's quadratic-exponential scheme, not Euler.* The SPX chain calibrates
to a parameter set that violates the Feller condition, which is normal for index options and
means the variance process spends real time near zero. Euler puts it below zero there, and
every repair for that - absorbing, reflecting, truncating - biases the price of exactly the
deep out-of-the-money puts this liability is made of. QE matches the first two moments of the
exact transition and cannot go negative.

*The short rate is exact, not discretised.* Over one step the pair (the rate at the end, the
integral of the rate across the step) is jointly normal with closed-form moments. The
integral is what discounts the cash flows, so a scheme that gets the rate right and the
integral wrong misprices a forty-year annuity while looking fine on a yield chart.

*The market is simulated on a fine grid and then aggregated to policy years.* Every event in
the contract lands on an anniversary: the withdrawal, the step-up, the rider charge. Between
anniversaries the only things that matter are the growth factor of the sub-account and the
discount factor, and both are integrals a fine simulation produces directly. So the dynamics
run fortnightly and the liability recursion runs on annual factors. That is not an
approximation to the contract, it is the contract, and it buys an order of magnitude in the
loop that a two-hundred-cohort book with Greeks has to run dozens of times.

The default of twenty-four steps a year was chosen by measuring, not by taste. Against COS
prices with rates held deterministic, twelve steps overprices a one-year at-the-money put by
1.1% and a 20%-out-of-the-money put by 2.1%, which is a bias several times the Monte Carlo
error and all in the same direction. The calibrated variance mean-reverts with a time
constant near two and a half months, so twelve steps is simply too coarse to resolve it.
Twenty-four steps brings every tested strike and maturity inside Monte Carlo error, and
fifty-two and a hundred and four change nothing further. The table is regenerated by
``scripts/run_market_validation.py``.

None of it is trusted without ``martingale_report``. If the discounted index is not a
martingale, or if expected discount factors do not reproduce the quoted curve, nothing
downstream means anything.
"""

from __future__ import annotations

from dataclasses import dataclass

import numpy as np

from .heston_cos import HestonParameters
from .hull_white import HullWhite

PSI_CRITICAL = 1.5          # Andersen's switch between the two QE branches
GAMMA1 = 0.5                # central discretisation of the variance integral
GAMMA2 = 0.5


@dataclass(frozen=True)
class Correlations:
    """The pairwise correlations, and what each one does.

    ``equity_variance`` is Heston's rho and comes from the option calibration; it is the
    skew. ``equity_rate`` is estimated from history and decides whether a sell-off arrives
    with falling rates, which is the state that hurts this liability most. ``variance_rate``
    is zero: it is weakly identified by anything free, and the quadratic-exponential variance
    draw is not a Gaussian increment, so imposing a correlation on it would be imposing it on
    the wrong object.
    """

    equity_variance: float
    equity_rate: float
    variance_rate: float = 0.0

    def __post_init__(self) -> None:
        for name in ("equity_variance", "equity_rate", "variance_rate"):
            value = getattr(self, name)
            if not -1.0 < value < 1.0:
                raise ValueError(f"{name} must lie strictly inside (-1, 1); got {value}")
        if self.variance_rate != 0.0:
            raise NotImplementedError(
                "a non-zero variance-rate correlation is not implemented; the QE variance "
                "draw is not a Gaussian increment and cannot carry one honestly"
            )


@dataclass(frozen=True)
class SubAccountMix:
    """The contract holder's fund allocation, as a portfolio rather than a scaled index.

    Jackson discloses the separate account split by fund type and nothing finer: at
    31 December 2025, equity 171,046, bond 19,711, balanced 43,317 and money market 2,332 out
    of 236,406, in millions. A guarantee written over that is not a guarantee over the S&P
    500, and a hedge that trades the index alone carries the difference as basis.

    ``tracking_error`` is the part of the equity sleeve no index instrument reaches: the
    sub-accounts are managed funds. Jackson names "correlations of market index returns to
    fund returns" as a model input and publishes nothing about it, and no free series
    identifies it, so it is a scenario parameter - zero by default, swept rather than fitted.
    Putting a number on it and calling it calibrated would be inventing one.
    """

    equity: float
    bond: float
    balanced: float
    money_market: float
    bond_duration: float = 6.0
    balanced_equity_share: float = 0.60
    tracking_error: float = 0.0

    def __post_init__(self) -> None:
        total = self.equity + self.bond + self.balanced + self.money_market
        if abs(total - 1.0) > 1e-6:
            raise ValueError(f"sub-account weights must sum to 1, got {total}")
        if self.bond_duration <= 0:
            raise ValueError("bond_duration must be positive")
        if self.tracking_error < 0:
            raise ValueError("tracking_error must not be negative")

    @property
    def equity_weight(self) -> float:
        """Sensitivity of the contract value to a move in the equity index.

        This is the number an equity shock is multiplied by. A 10% index fall does not take
        10% off a contract value that is a fifth in bonds.
        """
        return self.equity + self.balanced * self.balanced_equity_share

    @property
    def bond_weight(self) -> float:
        return self.bond + self.balanced * (1.0 - self.balanced_equity_share)

    @classmethod
    def all_equity(cls) -> "SubAccountMix":
        return cls(equity=1.0, bond=0.0, balanced=0.0, money_market=0.0)

    @classmethod
    def from_config(cls, cfg: dict) -> "SubAccountMix":
        m = cfg["subaccount_mix"]
        return cls(
            equity=float(m["equity"]),
            bond=float(m["bond"]),
            balanced=float(m["balanced"]),
            money_market=float(m["money_market"]),
            bond_duration=float(m["bond_duration"]),
            balanced_equity_share=float(m["balanced_equity_share"]),
            tracking_error=float(m.get("tracking_error", 0.0)),
        )


@dataclass(frozen=True)
class MarketPaths:
    """Annual factors, which is all the liability recursion needs.

    ``fund_growth`` is the gross total return of the sub-account over each policy year, before
    any charge. ``discount`` is the stochastic discount factor from time zero to the end of
    each year. The rest are state variables carried for hedging, for the regression proxy and
    for diagnostics.
    """

    fund_growth: np.ndarray        # (n_paths, n_years)
    index_growth: np.ndarray       # (n_paths, n_years), the equity index alone
    discount: np.ndarray           # (n_paths, n_years), cumulative from time zero
    short_rate: np.ndarray         # (n_paths, n_years), at each year end
    variance: np.ndarray           # (n_paths, n_years), at each year end
    zero_10y: np.ndarray           # (n_paths, n_years), ten-year zero rate at each year end
    realised_variance: np.ndarray  # (n_paths, n_years), average variance across each year
    seed: int
    antithetic: bool

    @property
    def n_paths(self) -> int:
        return self.fund_growth.shape[0]

    @property
    def n_years(self) -> int:
        return self.fund_growth.shape[1]

    def year_end_times(self) -> np.ndarray:
        return np.arange(1, self.n_years + 1, dtype=float)


def simulate(
    heston: HestonParameters,
    hull_white: HullWhite,
    correlations: Correlations,
    mix: SubAccountMix,
    n_years: int,
    n_paths: int,
    seed: int,
    steps_per_year: int = 24,
    antithetic: bool = True,
    chunk_paths: int = 20000,
) -> MarketPaths:
    """Simulate under the risk-neutral measure and return annual factors.

    There is deliberately no equity shock argument. Under Heston the return distribution does
    not depend on the index level, so an instantaneous shock changes nothing about the paths;
    it only changes the account value the paths start from, and the valuation engine applies
    it there, scaled by the sub-account's equity weight. Putting it here as well would double
    count it.

    ``antithetic`` mirrors every normal in the second half of the paths, and mirrors the
    variance scheme's uniforms as 1-U so the pairing still means something in the exponential
    branch.
    """
    if n_paths <= 0 or n_years <= 0:
        raise ValueError("n_paths and n_years must be positive")
    if antithetic and n_paths % 2:
        raise ValueError("antithetic sampling needs an even n_paths")
    if steps_per_year < 1:
        raise ValueError("steps_per_year must be at least 1")

    names = (
        "fund_growth", "index_growth", "discount", "short_rate",
        "variance", "zero_10y", "realised_variance",
    )
    out = {name: np.empty((n_paths, n_years)) for name in names}

    block = chunk_paths if not antithetic else max(2, (chunk_paths // 2) * 2)
    for start in range(0, n_paths, block):
        stop = min(start + block, n_paths)
        piece = _simulate_chunk(
            heston, hull_white, correlations, mix,
            n_years, stop - start, seed + start, steps_per_year, antithetic,
        )
        for name in names:
            out[name][start:stop] = piece[name]

    return MarketPaths(seed=seed, antithetic=antithetic, **out)


def _simulate_chunk(
    heston, hull_white, correlations, mix, n_years, n_paths, seed, steps_per_year, antithetic
):
    dt = 1.0 / steps_per_year
    n_steps = n_years * steps_per_year
    rng = np.random.default_rng(seed)
    half = n_paths // 2 if antithetic else n_paths

    def normals(count):
        draw = rng.standard_normal((half, count))
        return np.concatenate([draw, -draw], axis=0) if antithetic else draw

    def uniforms(count):
        draw = rng.random((half, count))
        return np.concatenate([draw, 1.0 - draw], axis=0) if antithetic else draw

    z_var = normals(n_steps)
    u_var = uniforms(n_steps)
    z_perp = normals(n_steps)
    z_rate_raw = normals(n_steps)
    z_rate_extra = normals(n_steps)
    z_basis = normals(n_steps) if mix.tracking_error > 0 else None

    # The equity-rate correlation is imposed on the component of the equity Brownian that is
    # orthogonal to the variance, because the variance is not a Gaussian increment here. With
    # variance and rates independent, corr(W_S, W_r) comes out as sqrt(1 - rho^2) times what
    # is imposed, so invert that to hit the target.
    rho = heston.rho
    orthogonal_share = np.sqrt(1.0 - rho**2)
    c = correlations.equity_rate / orthogonal_share
    if abs(c) >= 1.0:
        raise ValueError(
            f"an equity-rate correlation of {correlations.equity_rate} is out of reach with "
            f"rho = {rho}; the ceiling is {orthogonal_share:.3f}"
        )
    z_rate = c * z_perp + np.sqrt(1.0 - c**2) * z_rate_raw

    kappa, theta, xi = heston.kappa, heston.theta, heston.xi
    decay, var_x, var_int, cov = hull_white.step_moments(dt)
    chol_b = cov / np.sqrt(var_x) if var_x > 0 else 0.0
    chol_c = np.sqrt(max(var_int - chol_b**2, 0.0))

    k0 = -rho * kappa * theta * dt / xi
    k1 = GAMMA1 * dt * (kappa * rho / xi - 0.5) - rho / xi
    k2 = GAMMA2 * dt * (kappa * rho / xi - 0.5) + rho / xi
    k3 = GAMMA1 * dt * (1.0 - rho**2)
    k4 = GAMMA2 * dt * (1.0 - rho**2)

    basis_drift = -0.5 * mix.tracking_error**2 * dt
    basis_vol = mix.tracking_error * np.sqrt(dt)

    variance = np.full(n_paths, heston.v0)
    x_rate = np.zeros(n_paths)
    log_index = np.zeros(n_paths)
    log_fund = np.zeros(n_paths)
    log_discount = np.zeros(n_paths)

    names = (
        "fund_growth", "index_growth", "discount", "short_rate",
        "variance", "zero_10y", "realised_variance",
    )
    result = {name: np.empty((n_paths, n_years)) for name in names}
    year_start_index = log_index.copy()
    year_start_fund = log_fund.copy()
    year_variance_sum = np.zeros(n_paths)

    exp_kdt = np.exp(-kappa * dt)
    step_b = hull_white.B(dt)
    weight_equity = mix.equity_weight
    weight_bond = mix.bond_weight
    weight_cash = mix.money_market

    for step in range(n_steps):
        t0 = step * dt
        t1 = t0 + dt

        # ---- variance: Andersen's quadratic-exponential transition
        m = theta + (variance - theta) * exp_kdt
        s2 = (
            variance * xi**2 * exp_kdt * (1.0 - exp_kdt) / kappa
            + theta * xi**2 * (1.0 - exp_kdt) ** 2 / (2.0 * kappa)
        )
        psi = s2 / np.maximum(m**2, 1e-300)

        inv_psi = 1.0 / np.maximum(psi, 1e-300)
        b2 = np.maximum(
            2.0 * inv_psi - 1.0 + np.sqrt(np.maximum(2.0 * inv_psi * (2.0 * inv_psi - 1.0), 0.0)),
            0.0,
        )
        v_quadratic = (m / (1.0 + b2)) * (np.sqrt(b2) + z_var[:, step]) ** 2

        p = np.clip((psi - 1.0) / (psi + 1.0), 0.0, 1.0 - 1e-12)
        beta = (1.0 - p) / np.maximum(m, 1e-300)
        u = u_var[:, step]
        v_exponential = np.where(
            u <= p, 0.0, np.log(np.maximum((1.0 - p) / np.maximum(1.0 - u, 1e-300), 1.0)) / beta
        )
        quadratic_branch = psi <= PSI_CRITICAL
        next_variance = np.where(quadratic_branch, v_quadratic, v_exponential)

        # Andersen's martingale correction. With K0 fixed the discounted index picks up a
        # small positive drift that compounds: at monthly steps it reached three percent by
        # year forty-two, which is larger than the Monte Carlo error and would have read as a
        # free lunch in every long-dated valuation. Replacing K0 path by path with the value
        # that makes the conditional expectation of the step exactly one removes it, because
        # the moment generating function of the variance draw is known in closed form on both
        # branches.
        k0_star = _martingale_k0(
            variance, m, b2, p, beta, quadratic_branch, k1, k2, k3, k4, k0
        )

        # ---- short rate: exact, jointly with its own integral across the step
        rate_shock = np.sqrt(var_x) * z_rate[:, step]
        integral_shock = chol_b * z_rate[:, step] + chol_c * z_rate_extra[:, step]
        x_before = x_rate
        integral_x = x_before * step_b + integral_shock
        x_rate = x_before * decay + rate_shock
        rate_integral = hull_white.deterministic_drift_integral(t0, t1) + integral_x

        # ---- equity total-return index, Andersen's QE-compatible log update
        diffusion = np.sqrt(np.maximum(k3 * variance + k4 * next_variance, 0.0))
        index_log_step = (
            rate_integral + k0_star + k1 * variance + k2 * next_variance
            + diffusion * z_perp[:, step]
        )
        log_index = log_index + index_log_step

        # ---- sub-account: a rebalanced portfolio of the three sleeves
        equity_step = np.exp(index_log_step)
        if z_basis is not None:
            equity_step = equity_step * np.exp(basis_drift + basis_vol * z_basis[:, step])
        cash_step = np.exp(rate_integral)
        bond_step = _rolling_bond_growth(hull_white, t0, t1, x_before, x_rate, mix.bond_duration)
        fund_step = weight_equity * equity_step + weight_bond * bond_step + weight_cash * cash_step
        log_fund = log_fund + np.log(np.maximum(fund_step, 1e-12))

        year_variance_sum += GAMMA1 * variance + GAMMA2 * next_variance
        log_discount = log_discount - rate_integral
        variance = next_variance

        if (step + 1) % steps_per_year == 0:
            year = (step + 1) // steps_per_year - 1
            short_rate_now = x_rate + hull_white.alpha(t1)
            result["index_growth"][:, year] = np.exp(log_index - year_start_index)
            result["fund_growth"][:, year] = np.exp(log_fund - year_start_fund)
            result["discount"][:, year] = np.exp(log_discount)
            result["short_rate"][:, year] = short_rate_now
            result["variance"][:, year] = variance
            result["zero_10y"][:, year] = hull_white.zero_rate(t1, 10.0, short_rate_now)
            result["realised_variance"][:, year] = year_variance_sum / steps_per_year
            year_start_index = log_index.copy()
            year_start_fund = log_fund.copy()
            year_variance_sum = np.zeros(n_paths)

    return result


def _martingale_k0(variance, m, b2, p, beta, quadratic_branch, k1, k2, k3, k4, k0_fallback):
    """The drift constant that makes one step of the index an exact martingale.

    The step is exp(K0 + K1*v + K2*v' + sqrt(K3*v + K4*v')*Z) with Z independent of v'. Taking
    the expectation over Z first leaves exp(K0 + K1*v + 0.5*K3*v) times the moment generating
    function of v' at A = K2 + 0.5*K4, and both QE branches have that in closed form: a
    non-central chi-square on the quadratic branch and a point mass plus an exponential on the
    other. Setting K0 to minus the log of the whole thing makes the conditional expectation
    one, path by path.

    A is negative for every parameter set this project calibrates to, so neither branch's
    validity condition binds. The guard is there because a different chain could flip the
    sign of rho over xi, and a silently invalid moment generating function would produce
    prices that look fine and are not.
    """
    a_q = m / (1.0 + b2)
    exponent = k2 + 0.5 * k4

    valid_quadratic = 2.0 * exponent * a_q < 1.0 - 1e-9
    denominator = np.where(valid_quadratic, 1.0 - 2.0 * exponent * a_q, 1.0)
    log_mgf_quadratic = exponent * a_q * b2 / denominator - 0.5 * np.log(denominator)

    valid_exponential = exponent < beta - 1e-9
    safe_gap = np.where(valid_exponential, beta - exponent, 1.0)
    log_mgf_exponential = np.log(np.maximum(p + (1.0 - p) * beta / safe_gap, 1e-300))

    log_mgf = np.where(quadratic_branch, log_mgf_quadratic, log_mgf_exponential)
    valid = np.where(quadratic_branch, valid_quadratic, valid_exponential)
    corrected = -(k1 + 0.5 * k3) * variance - log_mgf
    return np.where(valid, corrected, k0_fallback)


def _rolling_bond_growth(hull_white, t0, t1, x_start, x_end, duration):
    """Growth of a constant-maturity zero-coupon bond fund across one step.

    The fund holds a bond of the target maturity, holds it for the step, and rebalances back
    to that maturity. So the return is the price of the same bond one step older divided by
    its price at the start, which is two closed-form Hull-White prices.
    """
    r_start = x_start + hull_white.alpha(t0)
    r_end = x_end + hull_white.alpha(t1)
    start_price = hull_white.bond_price(t0, t0 + duration, r_start)
    end_price = hull_white.bond_price(t1, t0 + duration, r_end)
    return end_price / start_price


def martingale_report(
    paths: MarketPaths,
    hull_white: HullWhite,
    mix: SubAccountMix,
) -> "object":
    """Check the two identities every price downstream rests on.

    Under the risk-neutral measure the discounted total-return index is a martingale, so
    E[D(T) * X(T)] must be X(0) = 1 for every T. And E[D(T)] must be the discount factor the
    curve quotes, P(0,T), because that is what the Hull-White fit was built to reproduce.

    Both are reported as a z-score: the error divided by its own Monte Carlo standard error.
    A z of three or more at any maturity means the simulator is wrong, not noisy. Antithetic
    pairs are dependent, so the standard error is taken across pair averages.
    """
    import pandas as pd

    rows = []
    for year in range(paths.n_years):
        maturity = float(year + 1)
        discount = paths.discount[:, year]
        index_level = np.cumprod(paths.index_growth[:, : year + 1], axis=1)[:, -1]
        fund_level = np.cumprod(paths.fund_growth[:, : year + 1], axis=1)[:, -1]

        for label, sample, target in (
            ("bond", discount, float(hull_white.curve.discount(maturity))),
            ("index", discount * index_level, 1.0),
            ("sub_account", discount * fund_level, 1.0),
        ):
            mean, stderr = _mean_and_error(sample, paths.antithetic)
            rows.append(
                {
                    "maturity": maturity,
                    "quantity": label,
                    "target": target,
                    "estimate": mean,
                    "std_error": stderr,
                    "error": mean - target,
                    "z_score": (mean - target) / stderr if stderr > 0 else np.nan,
                }
            )
    frame = pd.DataFrame(rows)
    frame.attrs["equity_weight"] = mix.equity_weight
    return frame


def _mean_and_error(sample: np.ndarray, antithetic: bool) -> tuple[float, float]:
    n = sample.size
    if antithetic and n % 2 == 0:
        half = n // 2
        pairs = 0.5 * (sample[:half] + sample[half:])
        return float(pairs.mean()), float(pairs.std(ddof=1) / np.sqrt(half))
    return float(sample.mean()), float(sample.std(ddof=1) / np.sqrt(n))
